export const GENDER = [
  {
    id: 0,
    label: "Seçiniz",
  },
  { id: 1, label: "Erkek" },
  { id: 2, label: "Kadın" },
];

export const LOCATIONS = [
  {
    city_Id: 0,
    city_Name: "Seçiniz",
  },
  {
    city_Id: 1,
    city_Name: "Adana",
  },
  {
    city_Id: 2,
    city_Name: "Adıyaman",
  },
  {
    city_Id: 3,
    city_Name: "Afyonkarahisar",
  },
  { city_Id: 4, city_Name: "İstanbul" },
  { city_Id: 5, city_Name: "Ankara" },
  { city_Id: 6, city_Name: "İzmir" },
  { city_Id: 7, city_Name: "Bursa" },
  { city_Id: 8, city_Name: "Antalya" },
  { city_Id: 9, city_Name: "Aydın" },
  { city_Id: 10, city_Name: "Balıkesir" },
  { city_Id: 11, city_Name: "Çanakkale" },
];

export const FAMILIES = [
  {
    id: 0,
    label: "Seçiniz",
    clicked: false,
  },
  {
    id: 1,
    label: "Kendim",
    clicked: false,
  },
  {
    id: 2,
    label: "Eşim",
    clicked: false,
  },
  {
    id: 3,
    label: "Kızım",
    clicked: false,
  },
  { id: 4, label: "Oğlum", clicked: false },
];

export const AGES = [
  { id: 0, label: 1 },
  { id: 1, label: 2 },
  { id: 2, label: 3 },
  { id: 3, label: 4 },
  { id: 4, label: 5 },
  { id: 5, label: 6 },
  { id: 6, label: 7 },
  { id: 7, label: 8 },
  { id: 8, label: 9 },
  { id: 9, label: 10 },
  { id: 10, label: 11 },
  { id: 11, label: 12 },
  { id: 12, label: 13 },
  { id: 13, label: 14 },
  { id: 14, label: 15 },
  { id: 15, label: 16 },
  { id: 16, label: 17 },
  { id: 17, label: 18 },
  { id: 18, label: 19 },
  { id: 19, label: 20 },
  { id: 20, label: 21 },
  { id: 21, label: 22 },
  { id: 22, label: 23 },
  { id: 23, label: 24 },
  { id: 24, label: 25 },
  { id: 25, label: 26 },
  { id: 26, label: 27 },
  { id: 27, label: 28 },
  { id: 28, label: 29 },
  { id: 29, label: 30 },
  { id: 30, label: 31 },
  { id: 31, label: 32 },
  { id: 32, label: 33 },
  { id: 33, label: 34 },
  { id: 34, label: 35 },
  { id: 35, label: 36 },
  { id: 36, label: 37 },
  { id: 37, label: 38 },
  { id: 38, label: 39 },
  { id: 39, label: 40 },
  { id: 40, label: 41 },
  { id: 41, label: 42 },
  { id: 42, label: 43 },
  { id: 43, label: 44 },
  { id: 44, label: 45 },
  { id: 45, label: 46 },
  { id: 46, label: 47 },
  { id: 47, label: 48 },
  { id: 48, label: 49 },
  { id: 49, label: 50 },
  { id: 50, label: 51 },
  { id: 51, label: 52 },
  { id: 52, label: 53 },
  { id: 53, label: 54 },
  { id: 54, label: 55 },
  { id: 55, label: 56 },
  { id: 56, label: 57 },
  { id: 57, label: 58 },
  { id: 58, label: 59 },
  { id: 59, label: 60 },
];

export const NETWORKS = [
  {
    id: 0,
    city: null,
    title: "Pembe",
    color: "#EB1C74",
    yatarakTedaviFiyat: 2070.9,
    yatarakveayaktaFiyat: 8758.7,
  },
  {
    id: 1,
    city: null,
    title: "Yeşil",
    color: "#44BD32",
    yatarakTedaviFiyat: 2148,
    yatarakveayaktaFiyat: 9625.97,
  },
  {
    id: 2,
    city: null,
    title: "Lacivert",
    color: "#1F2346",
    yatarakTedaviFiyat: 2944.8,
    yatarakveayaktaFiyat: 15003.84,
  },
];
